config/routes.rb
Classes::Application.routes.draw do
  
  root :to => "catalog#index"
  
  post :create, :to => "catalog#create"
  get :create, :to => "catalog#index"
  post "create_suggestion" => "catalog#create_suggestion"
  get "suggest" => "catalog#new_suggestion"
  get "autofill_user_fields" => "catalog#autofill_user_fields", :as => :autofill_user_fields
  get "category/:class_category_id", :to => "catalog#index", :as => :external_category
  
  scope "admin" do
    get "library_classes/expand_all", :to => "library_classes#expand_all"
    post "class_dates/send_follow_up", :to => "class_dates#send_follow_up", :as => :send_follow_up
    delete "suggestions/destroy_all", :to => "suggestions#clear_suggestions", :as => :clear_suggestions
    delete "clear_users", :to => "users#clear_users"
    delete "destroy_registration", :to => "users#destroy_registration"
    get "populate_sub_categories_select", :to => "library_classes#populate_sub_categories_select"
    resources :class_categories do
      put :sort, on: :collection
    end
    resources :class_sub_categories do
      put :sort, on: :collection
    end
    resources :library_classes do 
      put :sort, on: :collection
    end
    resources :class_dates 
    resources :users
    resources :registrations
    resources :response_emails
    resources :application_details
    resources :suggestions
  end
  
  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  match 'validate', :to => 'user_sessions#validate', :as => :validate
  resources :user_sessions

end

app/controllers/library_classes_controller.rb
class LibraryClassesController < ApplicationController
  before_filter :authenticate_admin
  respond_to :js, :html, :json
  
  # GET /library_classes
  def index
    @library_classes = LibraryClass.all
    @class_categories = ClassCategory.all
    respond_with(@library_classes)
  end

  # GET /library_classes/1
  def show
    @library_class = LibraryClass.find(params[:id])
    @class_date = ClassDate.new(params[:class_date])
    respond_with(@library_class)
  end
  
  # GET /library_classes/new
  def new
    @library_class = LibraryClass.new
    @class_categories = ClassCategory.all
    @class_category = ClassCategory.find(params[:library_class][:class_category_id]) unless params[:library_class].blank? or params[:library_class][:class_category_id].blank?
    @class_sub_categories = (@class_category.nil?) ? [] : @class_category.class_sub_categories
    respond_with(@library_class)
  end

  # GET /library_classes/1/edit
  def edit
    @library_class = LibraryClass.find(params[:id])
    @class_categories = ClassCategory.all
    @class_sub_categories = @library_class.class_category.class_sub_categories
    respond_with(@library_class)
  end

  # POST /library_classes
  def create
    @library_class = LibraryClass.new(params[:library_class])
    @class_categories = ClassCategory.all
    @class_category = ClassCategory.find(params[:library_class][:class_category_id]) unless params[:library_class][:class_category_id].blank?
    @class_sub_categories = (@class_category.nil?) ? [] : @class_category.class_sub_categories
    flash[:notice] = t('library_classes.flash.create.notice') if @library_class.save
    respond_with(@library_class)
  end
  
  # PUT /library_classes/1
  def update
    @library_class = LibraryClass.find(params[:id])
    flash[:notice] = t('library_classes.flash.update.notice') if @library_class.update_attributes(params[:library_class])
    @class_categories = ClassCategory.all
    @class_sub_categories = ClassSubCategory.find_all_by_class_category_id(@library_class.class_category_id)
    respond_with(@library_class)
  end

  # DELETE /library_classes/1
  def destroy
    @library_class = LibraryClass.find(params[:id])
    @library_class.destroy
    respond_with(@library_class)
  end
      
  # POST /library_classes/sort
  def sort
    @library_classes = LibraryClass.all

    params[:library_class].each_with_index do |id, index|
      LibraryClass.update_all(['position=?', index+1],['id=?',id])
    end 

    respond_with(@library_classes) do |format|
      format.js { render :nothing => true }
    end
  end
  
  # GET /library_classes/expand_all.js?expand_all=(true|false)
  def expand_all
    session[:expand_all] = (params[:expand_all] == "true") ? true : false
    render :nothing => true
  end
  
end

app/views/library_classes/_class_sub_categories.html.erb
<%= content_tag_for :li, class_sub_category do %>
<h3>
<button type="button" class="btn btn-link btn-small collapser" data-toggle="collapse" data-target="#sub_category_<%=class_sub_category.id%>_classes"><%= toggle_collapse_icon %></button>
<%= (class_sub_category.visible?) ? class_sub_category.title.html_safe : content_tag(:span, :class => "muted") { "#{class_sub_category.title} (inactive)".html_safe } %></h3>

	<ul id="sub_category_<%= class_sub_category.id %>_classes" class="classes_list collapse <%=collapse_class%>">
		<% class_sub_category.library_classes.each do |library_class| %>
			<%= render "library_class", :library_class => library_class %>
		<% end %>	
	</ul>
<% end %>

app/views/library_classes/_form.html.erb
<%= simple_form_for(@library_class) do |f| %>
	<%= f.input :title %>
	<%= f.input :class_category_id, prompt: "Select a category", as: :select, collection: @class_categories.map {|x| [strip_tags(x.title), x.id] }  %>
	<%= f.input :class_sub_category_id, as: :select, collection: @class_sub_categories.map {|x| [strip_tags(x.title), x.id] } %>
	<%= f.input :description, as: :text, :input_html => { :rows => 10 }, :hint => "HTML tags allowed: p, br, a, strong, em." %>
	<%= f.input :location %>
	<%= f.input :registration, as: :boolean, :label => "Registration required?" %>
	<%= f.input :alt_registration_text, as: :text, :input_html => { :rows => 10 }, :label => "Alternative registration text", :placeholder => "Default: Registration required. Select a date from this  list then fill out the form on the bottom of the page." %>
	<%= f.submit "Save" %>
<% end %>

app/views/library_classes/_library_class.html.erb
<%= content_tag_for :li, library_class do %>
	<h4><%= (library_class.visible?) ? sanitize_title(library_class.title) : content_tag(:span, :class => "muted") { "#{sanitize_title(library_class.title)} (inactive)" } %></h4>
	<div class="actions">
	<%= link_to 'Show', library_class %> |
	<%= link_to 'Edit', edit_library_class_path(library_class) %> |
	<%= link_to 'Destroy', library_class, :confirm => 'Are you sure?', :method => :delete, :remote => true %> |
	<%= link_to "#{(library_class.visible?) ? 'Hide' : 'Reveal' }", library_class_path(library_class, params.merge(:library_class => {:visible => !library_class.visible})), :method => :put,  :class => "toggle_visible", :remote => true %>
	</div>
<% end -%>

app/views/library_classes/create.js.erb
$("#new_library_class").replaceWith("<%=j render 'form'%>");

app/views/library_classes/destroy.js.erb
$("#library_class_<%=@library_class.id%>").remove();

app/views/library_classes/edit.html.erb
<h1>Editing class</h1>

<%= render "form" %>

<%= icon_tag :show %> <%= link_to 'Show', @library_class %> |
<%= icon_tag :back %> <%= link_to 'Back', library_classes_path %>

app/views/library_classes/index.html.erb
<div id="application_title">
	<div class="js_hide">
	<%= link_to "Edit title", edit_application_detail_url(format_text_by_purpose('application_title')) %>
	</div>
	<h1><%= icon_tag :edit %><%= best_in_place @application_title, :the_text, :display_with => lambda { |v| v.html_safe } %></h1>
</div>

<div id="application_head_text">
	<div class="js_hide">
	<%= link_to "Edit header", edit_application_detail_url(format_text_by_purpose('application_head_text')) %><br />
	</div>
	<%= icon_tag :edit %><%= best_in_place @application_head_text, :the_text, type: :textarea, :display_with => lambda { |v| v.html_safe } %>
</div>

<br />

<div id="expand_all_div">
<%= check_box_tag 'expand_all', nil, session[:expand_all] %><%= label_tag 'expand_all', "Expand all" %>
</div>

<div id="admin_list_classes" class="classes_container">
	
	<ul class="categories_list">
	<% @class_categories.each do |class_category| %>
		<%= content_tag_for :li, class_category do %>
			<h2><button type="button" class="btn btn-link btn-small collapser" data-toggle="collapse" data-target="#category_<%=class_category.id%>_list"><%=toggle_collapse_icon%></button>
				<%= (class_category.visible?) ? sanitize_title(class_category.title) : content_tag(:span, :class => "muted") { sanitize_title(class_category.title) + " (inactive)" } %></h2>
				<div id="category_<%=class_category.id%>_list" class="collapse <%=collapse_class%>">
					
					<!-- These are classes in the category without a sub category -->
					<ul id="category_<%=class_category.id%>_classes" class="classes_list">
					<% class_category.library_classes.without_sub_category.each do |library_class| %>
						<%= render "library_class", :library_class => library_class %>
					<% end %>
					</ul>
					
					<!-- These are classes inside sub-categories -->
					<ul id="category_<%=class_category.id%>_sub_categories" class="sub_categories_list">
					<% class_category.class_sub_categories.each do |class_sub_category| %>
						<%= render "class_sub_categories", :class_sub_category => class_sub_category %>
					<% end %>
					</ul>
					
				</div>
			<% end %>
		<% end %>
	</ul>
</div>

<br />

<div id="application_form_text">
	<div class="js_hide">
	<%= link_to "Edit footer", edit_application_detail_url(format_text_by_purpose('application_form_text')) %>
	</div>
	<div><%= icon_tag :edit %><%= best_in_place @application_form_text, :the_text, type: :textarea, :display_with => lambda { |v| v.html_safe } %></div>
</div>

<br />

<%= icon_tag :add %> <%= link_to 'New class', new_library_class_path %> 

app/views/library_classes/new.html.erb
<h1>New class</h1>

<%= render "form" %>

<%= icon_tag :back %> <%= link_to 'Back', library_classes_path %>

app/views/library_classes/show.html.erb
<p>
  <b>Title:</b>
  <%=h strip_tags(@library_class.title.html_safe) %>
</p>

<p>
  <b>Category:</b>
  <%=h strip_tags(@library_class.class_category.title) %>
</p>

<p>
  <b>Description:</b>
  <%= simple_format(sanitize(@library_class.description, :tags => %w(b strong i em br p a))) %> 
</p>

<p>
  <b>Location:</b>
  <%=h @library_class.location %>
</p>

<p>
  <b>Registration required?:</b>
  <%=h @library_class.registration %>
</p>

<p>
  <b>Alternative registration text:</b>
  <%= simple_format(sanitize(@library_class.alt_registration_text, :tags => %w(b strong i em br p a))) %> 
</p>

<div id="dates_display">
	<h3>Dates:</h3>
	<%= render :partial => "class_dates/index" %>
</div>

<div id="date_form"></div>

<div class="new_class_date well well-small">
<%= render "class_dates/new" %>
</div>

<%= icon_tag :edit %> <%= link_to 'Edit', edit_library_class_path(@library_class) %> |
<%= icon_tag :back %> <%= link_to 'Back', library_classes_path %>

app/views/library_classes/update.js.erb
// Replace library class entry on index page
$("#library_class_<%=@library_class.id%>").replaceWith("<%=j render 'library_class', :library_class => @library_class %>");
// Re render the form in _edit with selected subcategories
$(".edit_library_class").replaceWith("<%=j render 'form'%>");