config/routes.rb
Classes::Application.routes.draw do
  
  root :to => "catalog#index"
  
  post :create, :to => "catalog#create"
  get :create, :to => "catalog#index"
  post "create_suggestion" => "catalog#create_suggestion"
  get "suggest" => "catalog#new_suggestion"
  get "autofill_user_fields" => "catalog#autofill_user_fields", :as => :autofill_user_fields
  get "category/:class_category_id", :to => "catalog#index", :as => :external_category
  
  scope "admin" do
    get "library_classes/expand_all", :to => "library_classes#expand_all"
    post "class_dates/send_follow_up", :to => "class_dates#send_follow_up", :as => :send_follow_up
    delete "suggestions/destroy_all", :to => "suggestions#clear_suggestions", :as => :clear_suggestions
    delete "clear_users", :to => "users#clear_users"
    delete "destroy_registration", :to => "users#destroy_registration"
    get "populate_sub_categories_select", :to => "library_classes#populate_sub_categories_select"
    resources :class_categories do
      put :sort, on: :collection
    end
    resources :class_sub_categories do
      put :sort, on: :collection
    end
    resources :library_classes do 
      put :sort, on: :collection
    end
    resources :class_dates 
    resources :users
    resources :registrations
    resources :response_emails
    resources :application_details
    resources :suggestions
  end
  
  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  match 'validate', :to => 'user_sessions#validate', :as => :validate
  resources :user_sessions

end

app/models/class_category.rb
class ClassCategory < ActiveRecord::Base
  
  attr_accessible :title, :visible, :url, :external, :foot_text, :head_text
  validates_presence_of :title
  
  has_many :class_sub_categories, :dependent => :destroy
  has_many :library_classes, :dependent => :destroy
  
  default_scope order("class_categories.position ASC")
  scope :visible, where(:visible => true)

end

app/controllers/class_categories_controller.rb
class ClassCategoriesController < ApplicationController
  before_filter :authenticate_admin
  respond_to :js, :html
    
  # GET /class_categories
  def index
    @class_categories = ClassCategory.find(:all) 
    respond_with(@class_categories)
  end

  # GET /class_categories/1
  def show
    @class_category = ClassCategory.find(params[:id])
    @class_sub_category = ClassSubCategory.new
    respond_with(@class_category)
  end

  # GET /class_categories/new
  def new
    @class_category = ClassCategory.new
    respond_with(@class_category)
  end
  
  # POST /class_categories
  def create
    @class_category = ClassCategory.new(params[:class_category])    
    flash[:notice] = t('class_categories.flash.create.notice') if @class_category.save
    respond_with(@class_category)
  end

  # GET /class_categories/1/edit
  def edit
    @class_category = ClassCategory.find(params[:id])
    respond_with(@class_category)
  end

  # PUT /class_categories/1
  def update
    @class_category = ClassCategory.find(params[:id])
    flash[:notice] = t('class_categories.flash.update.notice') if @class_category.update_attributes(params[:class_category])
    @class_categories = ClassCategory.all
    respond_with(@class_category)
  end

  # DELETE /class_categories/1
  def destroy
    @class_category = ClassCategory.find(params[:id])
    flash[:notice] = t('class_categories.flash.destroy.notice') if @class_category.destroy
    respond_with(@class_category)
  end
 
  # POST /class_categories/sort
  def sort
    @class_categories = ClassCategory.all

    params[:class_category].each_with_index do |id, index|
      ClassCategory.update_all(['position=?', index+1],['id=?',id])
    end 

    respond_with(@class_categories) do |format|
      format.js { render :nothing => true }
    end
  end
end

app/helpers/class_categories_helper.rb
module ClassCategoriesHelper

  # Link to an category URL
  def link_to_class_category_url(class_category)
    if class_category.url?
      link_to(sanitize_title(class_category.title), class_category.url, :target => "_blank")
    else
      sanitize_title(class_category.title)
    end
  end
  
  # Link to an external category list
  def link_to_external_category(class_category)
    if class_category.external? and params[:class_category_id].blank?
      link_to(strip_tags(sanitize_title(class_category.title)), external_category_url(:class_category_id => "#{class_category.id}-#{parameterize_title(class_category.title)}"))
    else
      sanitize_title(class_category.title)
    end
  end
  
end

app/views/class_categories/_class_categories.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Title</th>
			<th>Options</th>
		</tr>
	</thead>
	<tbody>
		<% @class_categories.each do |category| %>
		<tr id="class-category-<%= category.id%>">
			<td id="class-category-title-<%= category.id%>">
				<% if category.visible? %>
					<%= sanitize_title(category.title) %>
				<% else %>
					<span class="muted"><%= sanitize_title(category.title) %></span>
				<% end %>
			</td>
			<td><%= link_to 'Show', category %></td>
			<td><%= link_to 'Edit', edit_class_category_path(category) %></td>
			<td><%= link_to 'Destroy', category, :confirm => 'Deleting this category will delete all sub-categories, classes and registrations associated with it. THIS ACTION CANNOT BE UNDONE. Are you sure you want to delete this category?', :method => :delete %></td>
			<td><%= link_to "#{(category.visible?) ? 'Hide' : 'Reveal' }", class_category_path(category, params.merge(:class_category => {:visible => !category.visible})), :method => :put,  :class => "toggle_visible", :remote => true %></td>
		</tr>
		<% end -%>
	</tbody>
</table>

app/views/class_categories/_class_sub_categories.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Title</th>
			<th>URL</th>
			<th>Options</th>
		</tr>
	</thead>
	<tbody>
	<% @class_category.class_sub_categories.each do |sub_category| %>
		<tr>
			<td>
				<% if sub_category.visible? %>
					<%= strip_tags(sub_category.title) %>
				<% else %>
					<span class="muted"><%= strip_tags(sub_category.title) %></span>
				<% end %>
			</td>
			<td><%=h sub_category.url %></td>
			<td><%= link_to 'Edit', edit_class_sub_category_path(sub_category) %></td>
			<td><%= link_to 'Destroy', sub_category, :confirm => 'Are you sure that you want to delete this sub category?', :method => :delete %></td>
			<td>
			<%= link_to "#{(sub_category.visible?) ? 'Hide' : 'Reveal' }", class_sub_category_path(sub_category, params.merge(:class_sub_category => {:visible => !sub_category.visible})), :method => :put,  :class => "toggle_visible", :remote => true %>
		<% end %>
	</tbody>
</table>

app/views/class_categories/_form.html.erb
<%= simple_form_for @class_category do |f| %>
	<%= f.input :title %>
	<%= f.input :external, :hint => "If a category is marked 'external' it will display as a link to another page with only its class listings." %>
	<%= f.input :url, :placeholder => "optional", :hint => "Not valid if external is checked." %>
	<%= f.input :head_text, :label => "Category header text", :placeholder => "optional", :hint => "This text will appear before the category listing", as: :text, :input_html => { :rows => 3 }%>
	<%= f.input :foot_text, :label => "Category footer text", :placeholder => "optional", :hint => "This text will appear after the category listing", as: :text, :input_html => { :rows => 3 }%>
	<%= f.submit "Save" %>
<% end %>

app/views/class_categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form" %>

<%= icon_tag :show %><%= link_to 'Show', @class_category %> |
<%= icon_tag :back %><%= link_to 'Back', class_categories_path %>

app/views/class_categories/index.html.erb
<h1>Listing Categories</h1>

<div id="class_categories">
<%= render "class_categories" %>
</div>

<br />

<%= icon_tag :add %> <%= link_to 'New category', new_class_category_path %>

app/views/class_categories/new.html.erb
<h1>New category</h1>

<%= render "form" %>

<%= icon_tag :back %> <%= link_to 'Back', class_categories_path %>

app/views/class_categories/show.html.erb
<p>
  <b>Title:</b>
  <%=h sanitize_title(@class_category.title) %>
</p>
<p>
  <b>External:</b>
  <%=h @class_category.external %>
</p>
<p>
  <b>URL:</b>
  <%=h @class_category.url %>
</p>
<p>
  <b>Header text:</b>
  <%= simple_format(sanitize(@class_category.head_text, :tags => %w(b strong i em br p a))) %> 
</p>
<p>
  <b>Footer text:</b>
  <%= simple_format(sanitize(@class_category.foot_text, :tags => %w(b strong i em br p a))) %> 
</p>

<p>
  <b>Sub categories:</b>
  <div id="class_sub_categories">
  <%= render "class_sub_categories" %>
  </div>
</p>

<div class="new_sub_categeory well well-small">
<%= render "class_sub_categories/new" %>
</div>

<%= icon_tag :edit %> <%= link_to 'Edit', edit_class_category_path(@class_category) %> |
<%= icon_tag :back %> <%= link_to 'Back', class_categories_path %>

app/views/class_categories/update.js.erb
$("#class_categories").html("<%=j render 'class_categories' %>")