config/routes.rb
Classes::Application.routes.draw do
  
  root :to => "catalog#index"
  
  post :create, :to => "catalog#create"
  get :create, :to => "catalog#index"
  post "create_suggestion" => "catalog#create_suggestion"
  get "suggest" => "catalog#new_suggestion"
  get "autofill_user_fields" => "catalog#autofill_user_fields", :as => :autofill_user_fields
  get "category/:class_category_id", :to => "catalog#index", :as => :external_category
  
  scope "admin" do
    get "library_classes/expand_all", :to => "library_classes#expand_all"
    post "class_dates/send_follow_up", :to => "class_dates#send_follow_up", :as => :send_follow_up
    delete "suggestions/destroy_all", :to => "suggestions#clear_suggestions", :as => :clear_suggestions
    delete "clear_users", :to => "users#clear_users"
    delete "destroy_registration", :to => "users#destroy_registration"
    get "populate_sub_categories_select", :to => "library_classes#populate_sub_categories_select"
    resources :class_categories do
      put :sort, on: :collection
    end
    resources :class_sub_categories do
      put :sort, on: :collection
    end
    resources :library_classes do 
      put :sort, on: :collection
    end
    resources :class_dates 
    resources :users
    resources :registrations
    resources :response_emails
    resources :application_details
    resources :suggestions
  end
  
  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  match 'validate', :to => 'user_sessions#validate', :as => :validate
  resources :user_sessions

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_accessible :fullname, :suggestion, :email, :user_id, :username
  
  validates :email, :allow_blank => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates_presence_of :suggestion
  
  before_create :populate_user_fields
  
  def populate_user_fields
    unless self.user_id.nil?
      user = User.find(self.user_id)
      self.fullname = "#{user.firstname} #{user.lastname}"
      self.email = user.email
      self.username = user.username
    end
  end
  
  # Simple SQL search for common suggestion attributes
  def self.search(search)
    if search
      q = "%#{search}%"
      where('fullname LIKE ? || suggestion LIKE ? || email LIKE ? || username LIKE ?', q, q, q, q)
    else
      scoped
    end
  end
  
  # Create a CSV format
  comma do
    created_at 'Date submitted' do |created_at| created_at.to_s end
    fullname 'Name'
    username 'NetID'
    email
    suggestion
  end
  
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_filter :authenticate_admin
  respond_to :html, :js, :csv
  
  # List suggestions with sort and search options
  def index
    @suggestions = Suggestion.search(params[:q]).sorted(params[:sort], "created_at ASC").page(params[:page]).per(30)
    respond_with(@suggestions)
  end
  
  # GET /suggestions/1
  def show
    @suggestion = Suggestion.find(params[:id])
    respond_with(@suggestion)
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
    respond_with(@suggestion)
  end

  # POST /suggestions
  def create
    @suggestion = Suggestion.new(params[:suggestion])

    respond_with(@suggestion) do |format|
      if @suggestion.save
        flash[:notice] = t('suggestions.flash.create.notice')
        format.html { redirect_to root_url }
      end
    end
  end

  # PUT /suggestions/1
  def update
    @suggestion = Suggestion.find(params[:id])
    flash[:notice] = t('suggestions.flash.update.notice') if @suggestion.update_attributes(params[:suggestion])
    respond_with(@suggestion)
  end

  # DELETE /suggestions/1
  def destroy
    @suggestion = Suggestion.find(params[:id])
    flash[:notice] = t('suggestions.flash.destroy.notice') if @suggestion.destroy
    respond_with(@suggestion)
  end
  
  # Destroy all suggestions
  def clear_suggestions
    flash[:notice] = "Cleared all suggestions." if Suggestion.destroy_all
    redirect_to suggestions_url
  end
  
end

app/views/suggestions/_form.html.erb
<%= simple_form_for @suggestion do |f| %>
	<%= f.input :fullname, label: 'Name' %>
	<%= f.input :email, placeholder: 'user@nyu.edu' %>
	<%= f.input :suggestion, as: :text, :input_html => { :rows => 3 } %>
	<%= f.button :submit, "Suggest" %>
<% end %>

app/views/suggestions/_suggestions.html.erb
<p><%= page_entries_info @suggestions %></p>

<%= paginate @suggestions, :theme => "bootstrap" %>

<div class="btn-group">
  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
    Action
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to suggestions_url(:format => :csv) do %><i class="icon-download-alt"></i> Download as CSV<% end -%></li>
  </ul>
</div>

<div class="btn-group">
  <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
    Delete
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to clear_suggestions_url, :data => {:confirm => 'This will delete all suggestions and cannot be undone. Are you sure?'}, :method => :delete do %><i class="icon-ban-circle"></i> Clear all suggestions<% end -%></li>
  </ul>
</div>

<br /><br />

<table class="table table-striped">
	<thead>
		<tr>
			<th><%= link_to_sorted "Date submitted", 'created_at' %></th>
			<th><%= link_to_sorted "Name", "fullname" %></th>
			<th><%= link_to_sorted "Username", "username" %></th>
			<th><%= link_to_sorted "Email", "email" %></th>
			<th>Suggestion</th>
			<th>Options</th>
		</tr>
	</thead>
	<tbody>
	<% @suggestions.each do |suggestion| %>
		<tr>
			<td><%=h suggestion.created_at.to_date.to_s %></td>
			<td><%=h suggestion.fullname %></td>
			<td><%= link_to suggestion.username, user_path(suggestion.user_id) unless suggestion.user_id.blank? %></td>
			<td><%=h suggestion.email %></td>
			<td><%= content_tag :abbr, truncate(suggestion.suggestion, :length => 140), :title => suggestion.suggestion %></td>
			<td><%= link_to 'Show', suggestion %></td>
			<td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
			<td><%= link_to 'Destroy', suggestion, :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<%= paginate @suggestions, :theme => "bootstrap" %>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render "form" %>

<%= icon_tag :show %> <%= link_to 'Show', @suggestion %> | 
<%= icon_tag :back %> <%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Listing suggestions</h1>

<%= form_tag suggestions_path, :class => "form-inline clearfix", :method => :get do %>
  <p>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div class="input-append pull-left">
      <%= label_tag :q, "Search...", :class => "hide-text" %>
      <%= text_field_tag :q, nil, :class => "search_q q", :placeholder => "Search..." %>
      <%= button_tag(:type => 'button', :id => "search", :class => "btn btn-primary search-btn") do
        content_tag(:span, 'Search', :class => "submit-search-text")+"     "+
        content_tag(:i, nil, :class => "icon-search icon-white")
      end %>
    </div>
  </p>
<% end %>

<div>
<%= render :partial => "suggestions" %>
</div>

app/views/suggestions/show.html.erb
<p>
  <b>Name:</b>
  <%=h @suggestion.fullname %>
</p>

<p>
  <b>Username:</b>
  <%= link_to @suggestion.username, user_url(@suggestion.user_id) unless @suggestion.user_id.nil? %>
</p>

<p>
  <b>Email:</b>
  <%=h @suggestion.email %>
</p>

<p>
  <b>Suggestion:</b>
  <%=h @suggestion.suggestion %>
</p>

<%= icon_tag :edit %> <%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= icon_tag :back %> <%= link_to 'Back', suggestions_path %>