config/routes.rb
Classes::Application.routes.draw do
  
  root :to => "catalog#index"
  
  post :create, :to => "catalog#create"
  get :create, :to => "catalog#index"
  post "create_suggestion" => "catalog#create_suggestion"
  get "suggest" => "catalog#new_suggestion"
  get "autofill_user_fields" => "catalog#autofill_user_fields", :as => :autofill_user_fields
  get "category/:class_category_id", :to => "catalog#index", :as => :external_category
  
  scope "admin" do
    get "library_classes/expand_all", :to => "library_classes#expand_all"
    post "class_dates/send_follow_up", :to => "class_dates#send_follow_up", :as => :send_follow_up
    delete "suggestions/destroy_all", :to => "suggestions#clear_suggestions", :as => :clear_suggestions
    delete "clear_users", :to => "users#clear_users"
    delete "destroy_registration", :to => "users#destroy_registration"
    get "populate_sub_categories_select", :to => "library_classes#populate_sub_categories_select"
    resources :class_categories do
      put :sort, on: :collection
    end
    resources :class_sub_categories do
      put :sort, on: :collection
    end
    resources :library_classes do 
      put :sort, on: :collection
    end
    resources :class_dates 
    resources :users
    resources :registrations
    resources :response_emails
    resources :application_details
    resources :suggestions
  end
  
  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  match 'validate', :to => 'user_sessions#validate', :as => :validate
  resources :user_sessions

end

app/views/common/_flash_msg.html.erb
<div class="flash_messages">
<% [:success, :notice, :error, :alert].each do |type| %>
	<%- alert_class = type == :notice ? 'info' : type %>
	<% unless flash[type].blank? %>
		<% if flash[type].is_a? Array %>
			<% flash[type].each do |msg| %>
			<div class="alert alert-<%=alert_class%>"><%= msg %>
			<a class="close" data-dismiss="alert" href="#">x</a>
			</div>
			<% end %>
		<% else %>
		<div class="alert alert-<%=alert_class%>"><%= flash[type] %>
			<a class="close" data-dismiss="alert" href="#">x</a>
		</div>
		<% end %>
	<% end %>
<% end %>
</div>

app/views/common/_sidebar.html.erb
<% if is_admin? %>
<%= sidebar_section("admin_panel", content_tag(:h2, "Admin Panel"), true) do %>
    <ul class="admin_options">
		<li><%= link_to "Manage Categories", class_categories_path %></li>
		<li><%= link_to "Manage Classes", library_classes_path %></li>
		<li><%= link_to "Manage Response E-mails", response_emails_path %></li>
		<li><%= link_to "Manage Users", users_path %></li>
		<li><%= link_to "View Class Suggestions", suggestions_path %></li>
    </ul>
<% end -%>
<% end %>